[tool.poetry]
name = "csawesome_to_replit"
version = "1.0.0"
description = ""
authors = ["Jaden Peterson"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
selenium = "^3.141.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
